apiVersion: v1
kind: Service
metadata:
  name: {{ include "bevo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "bevo.fullname" . }}
    helm.sh/chart: {{ include "bevo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ingress-dotnet
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: {{ .Values.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ingress-dotnet
    app.kubernetes.io/instance: {{ .Release.Name }}
